/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef RANDOMPING_PRIVATE_H
#define RANDOMPING_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"6.11.11.17"
#define VER_MAJOR	6
#define VER_MINOR	11
#define VER_RELEASE	11
#define VER_BUILD	17
#define COMPANY_NAME	"MBSinc"
#define FILE_VERSION	"6.11.11.17"
#define FILE_DESCRIPTION	"Developed using the Dev-C++ IDE"
#define INTERNAL_NAME	"UMBRELLA-RANDOM PING"
#define LEGAL_COPYRIGHT	"©2016 Bagus Saputra"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"UMBRELLA-RANDOM PING"
#define PRODUCT_VERSION	"6.11.11.17"

#endif /*RANDOMPING_PRIVATE_H*/
