if %a%==1 set resa=0
if %a%==2 set resa=1
if %a%==3 set resa=2
if %a%==4 set resa=3
if %a%==5 set resa=4
if %a%==6 set resa=5
if %a%==7 set resa=6
if %a%==8 set resa=7
if %a%==9 set resa=8
if %a%==10 set resa=9
if %a%==11 set resa=a
if %a%==12 set resa=b
if %a%==13 set resa=c
if %a%==14 set resa=d
if %a%==15 set resa=e
if %a%==16 set resa=f
if %a%==17 set resa=g
if %a%==18 set resa=h
if %a%==19 set resa=i
if %a%==20 set resa=j
if %a%==21 set resa=k
if %a%==22 set resa=l
if %a%==23 set resa=m
if %a%==24 set resa=n
if %a%==25 set resa=o
if %a%==26 set resa=p
if %a%==27 set resa=q
if %a%==28 set resa=r
if %a%==29 set resa=s
if %a%==30 set resa=t
if %a%==31 set resa=u
if %a%==32 set resa=v
if %a%==33 set resa=w
if %a%==34 set resa=x
if %a%==35 set resa=y
if %a%==36 set resa=z
if %a%==37 set resa=A
if %a%==38 set resa=B
if %a%==39 set resa=C
if %a%==40 set resa=D
if %a%==41 set resa=E
if %a%==42 set resa=F
if %a%==43 set resa=G
if %a%==44 set resa=H
if %a%==45 set resa=I
if %a%==46 set resa=J
if %a%==47 set resa=K
if %a%==48 set resa=L
if %a%==49 set resa=M
if %a%==50 set resa=N
if %a%==51 set resa=O
if %a%==52 set resa=P
if %a%==53 set resa=Q
if %a%==54 set resa=R
if %a%==55 set resa=S
if %a%==56 set resa=T
if %a%==57 set resa=U
if %a%==58 set resa=V
if %a%==59 set resa=W
if %a%==60 set resa=X
if %a%==61 set resa=Y
if %a%==62 set resa=Z